#!groovy
def DEV_PROJECTNAME = "ndgaikwad-dev"
def UAT_PROJECTNAME = "ndgaikwad-stage"
def BUILDCONFIGNAME="hrappnil1"
def IMAGE_NAME="hrappnil1:latest"
def UATIMAGENAME = "hrappnil1:UATReady-1.0.0"
node('dotnetcore31') {
   stage('Build Image') {    
    sh "oc -n $DEV_PROJECTNAME new-app --name=$BUILDCONFIGNAME dotnet:3.1~https://github.com/ndgaikwad/OpenShiftHrOffice#master --context-dir HrOffice --source-secret nil-at-github"    
    sh "oc expose service $BUILDCONFIGNAME"
    sh "oc -n $DEV_PROJECTNAME tag $DEV_PROJECTNAME/$IMAGE_NAME $UAT_PROJECTNAME/$UATIMAGENAME"
  }
}
