#!groovy
def DEV_PROJECTNAME = "ndgaikwad-dev"
def UAT_PROJECTNAME = "ndgaikwad-stage"
def BUILDCONFIGNAME="hrappnil1"
def IMAGE_NAME="hrappnil1:latest"
def UATIMAGENAME = "hrappnil1:UATReady-1.0.0"
node('dotnetcore31') {
  stage('Clone') {
    checkout scm
  }
  stage('Build Image') {
    sh "oc -n $DEV_PROJECTNAME start-build $BUILDCONFIGNAME --from-dir=../HrOffice/dist --follow"
    sh "oc -n $DEV_PROJECTNAME tag $DEV_PROJECTNAME/$IMAGE_NAME $UAT_PROJECTNAME/$UATIMAGENAME"
  }
}
